-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "FIRE_INCIDENTS" (
    "ID" int   NOT NULL,
    "FIRE_NAME" string   NOT NULL,
    "FIRE_STARTED_DATE" DATE   NOT NULL,
    "FIRE_EXTINGUISHED_DATE" DATE   NOT NULL,
    "YEAR" int   NOT NULL,
    "COUNTY_ID" int   NOT NULL,
    "PERCENT_CONTAINED" int   NOT NULL,
    "TOTAL_ACRES_BURNED" int   NOT NULL,
    CONSTRAINT "pk_FIRE_INCIDENTS" PRIMARY KEY (
        "ID"
     )
);

CREATE TABLE "FIRE_FACTS" (
    "ID" int   NOT NULL,
    "FIRE_NAME" string   NOT NULL,
    "YEAR" int   NOT NULL,
    "STATE" string   NOT NULL,
    "FIRE_ALARM_DATE" date   NOT NULL,
    "FIRE_CONTAINED_DATE" date   NOT NULL,
    "FIRE_CAUSE" int   NOT NULL,
    CONSTRAINT "pk_FIRE_FACTS" PRIMARY KEY (
        "ID"
     )
);

CREATE TABLE "FIRE_IMPACTS" (
    "ID" int   NOT NULL,
    "FIRE_NAME" string   NOT NULL,
    "TOTAL_ACRES_BURNED" int   NOT NULL,
    "COUNTY_ID" int   NOT NULL,
    "FIRE_INJURIES" int   NOT NULL,
    "STRUCTURES_DAMAGED" int   NOT NULL,
    "STRUCTURES_DESTROYED" int   NOT NULL,
    "STRUCTURES_EVACUVATED" int   NOT NULL,
    "STRUCTURES_THREATENED" int   NOT NULL,
    "FIRE_SHAPE" int   NOT NULL,
    "FIRE_LENGTH" int   NOT NULL,
    CONSTRAINT "pk_FIRE_IMPACTS" PRIMARY KEY (
        "ID"
     )
);

CREATE TABLE "FIRE_LOCATIONS" (
    "ID" int   NOT NULL,
    "FIRE_NAME" string   NOT NULL,
    "COUNTY_ID" int   NOT NULL,
    "COUNTY_NAME" string   NOT NULL,
    "LATITUDE" int   NOT NULL,
    "LONGITUDE" int   NOT NULL,
    CONSTRAINT "pk_FIRE_LOCATIONS" PRIMARY KEY (
        "ID"
     )
);

CREATE TABLE "FIRE_CAUSE" (
    "ID" int   NOT NULL,
    "CAUSE_ID" int   NOT NULL,
    "CAUSE_DESCRIPTION" string   NOT NULL,
    CONSTRAINT "pk_FIRE_CAUSE" PRIMARY KEY (
        "ID"
     )
);

ALTER TABLE "FIRE_FACTS" ADD CONSTRAINT "fk_FIRE_FACTS_FIRE_NAME" FOREIGN KEY("FIRE_NAME")
REFERENCES "FIRE_INCIDENTS" ("FIRE_NAME");

ALTER TABLE "FIRE_FACTS" ADD CONSTRAINT "fk_FIRE_FACTS_FIRE_CAUSE" FOREIGN KEY("FIRE_CAUSE")
REFERENCES "FIRE_CAUSE" ("CAUSE_ID");

ALTER TABLE "FIRE_IMPACTS" ADD CONSTRAINT "fk_FIRE_IMPACTS_FIRE_NAME" FOREIGN KEY("FIRE_NAME")
REFERENCES "FIRE_INCIDENTS" ("FIRE_NAME");

ALTER TABLE "FIRE_LOCATIONS" ADD CONSTRAINT "fk_FIRE_LOCATIONS_FIRE_NAME_COUNTY_ID" FOREIGN KEY("FIRE_NAME", "COUNTY_ID")
REFERENCES "FIRE_INCIDENTS" ("FIRE_NAME", "COUNTY_ID");

CREATE INDEX "idx_FIRE_INCIDENTS_FIRE_NAME"
ON "FIRE_INCIDENTS" ("FIRE_NAME");

